name: Build and Deploy

# 在deploy分支发生push事件时触发。
on: 
  push:
    branches:
      - deploy # deploy分支有push时触发

# 设置环境变量
env:
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest #运行在虚拟机环境的ubuntu-latest

    steps:
      - name: Checkout # 01. 检出仓库的最新分支代码
      - uses: actions/checkout@master # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.LJ_WEBSITE_DEPLOY }}
          # TARGET_REPO: luojing1336/lj-website
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist/
          COMMIT_MESSAGE: Auto deploy from Github Actions
          # CNAME: https://www.xxx.com
